# Generated by Django 4.0.4 on 2022-05-02 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('pressure', models.CharField(max_length=6)),
                ('date_of_create', models.DateField(auto_now=True, verbose_name='Create time')),
                ('date_of_update', models.DateField(auto_now=True, verbose_name='Update time')),
            ],
            options={
                'ordering': ['pressure', 'date_of_create'],
            },
        ),
    ]
